# Generated by Django 5.0 on 2023-12-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/avatares"),
        ),
    ]
